apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-trust-vol
  name: kafka-trust-vol
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  volumeName: kafka-vol
status: {}
