apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-vol
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp2
  volumeMode: Filesystem
  volumeName: kafka-vol
  awsElasticBlockStore:
    volumeID: 'aws://us-east-2c/vol-04c9c96d5a5fae7c6'
    fsType: ext4


