apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-vol
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp2
  volumeMode: Filesystem
  volumeName: kafka-vol
  awsElasticBlockStore:
    fsType: ext4


